name: ZUI | Hybrid Example
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
include: ['_pages']
baseurl: '/zui-prototypes'

collections:
  pages:
    output: true
    permalink: /:path/

baseurl: '/zui-prototypes'